//Autenticacion
export const REGISTRO_EXITOSO = "RREGISTRO_EXITOSO"
export const REGISTRO_ERROR = "REGISTRO_ERROR"
export const LOGIN_EXITOSO = "LOGIN_EXITOSO"
export const LOGIN_ERROR = "LOGIN_ERROR"
export const USUARIO_AUTENTICADO = "USUARIO_AUTENTICADO"
export const CERRAR_SESION = "CERRAR_SESION"
export const LIMPIAR_STATE = "LIMPIAR_STATE"
//Alerta
export const OCULTAR_ALERTA = "OCULTAR_ALERTA"
//Producto
export const AGREGAR_PRODUCTO = "AGREGAR_PRODUCTO"
export const ERROR_AGREGAR_PRODUCTO = "ERROR_AGREGAR_PRODUCTO"
export const OBTENER_PRODUCTOS = "OBTENER_PRODUCTOS"
export const PRODUCTOS_CAMBIADOS = "PRODUCTOS_CAMBIADOS"
export const PRODUCTO_ACTUAL = "PRODUCTO_ACTUAL"
export const EDITAR_PRODUCTO = "EDITAR_PRODUCTO"
export const LIMPIAR_SELECCIONADO = "LIMPIAR_SELECCIONADO"
export const ELIMINAR_PRODUCTO = "ELIMINAR_PRODUCTO"
export const FILTRAR_PRODUCTO = "FILTRAR_PRODUCTO"
export const ELIMINAR_PRODUCTOS = "ELIMINAR_PRODUCTOS"
export const ORDENAR_CODIGO = "ORDENAR_CODIGO"
export const ORDENAR_CODIGO_FILTRADO = "ORDENAR_CODIGO_FILTRADO"
export const ORDENAR_PRECIO = "ORDENAR_PRECIO"
export const ORDENAR_PRECIO_FILTRADO = "ORDENAR_PRECIO_FILTRADO"
export const ORDENAR_NOMBRE = "ORDENAR_NOMBRE"
export const ORDENAR_NOMBRE_FILTRADO = "ORDENAR_NOMBRE_FILTRADO"
export const ORDENAR_MARCA = "ORDENAR_MARCA"
export const ORDENAR_MARCA_FILTRADO = "ORDENAR_MARCA_FILTRADO"
export const ORDENAR_MODELO = "ORDENAR_MODELO"
export const ORDENAR_MODELO_FILTRADO = "ORDENAR_MODELO_FILTRADO"
export const ORDENAR_DISPONIBLES = "ORDENAR_DISPONIBLES"
export const ORDENAR_DISPONIBLES_FILTRADO = "ORDENAR_DISPONIBLES_FILTRADO"





//Faltantes
export const AGREGAR_FALTANTE = "AGREGAR_FALTANTE"
export const ELIMINAR_FALTANTE = "ELIMINAR_FALTANTE"
export const TRAER_FALTANTES = "TRAER_FALTANTES"
export const FILTRO_FALTANTE = "FILTRO_FALTANTE"
export const ORDENAR_CODIGO_FALTANTE = "ORDENAR_CODIGO_FALTANTE"
export const ORDENAR_NOMBRE_FALTANTE = "ORDENAR_NOMBRE_FALTANTE"
export const ORDENAR_MARCA_FALTANTE = "ORDENAR_MARCA_FALTANTE"
export const ORDENAR_MODELO_FALTANTE = "ORDENAR_MODELO_FALTANTE"
export const ORDENAR_RUBRO_FALTANTE = "ORDENAR_RUBRO_FALTANTE"
export const ORDENAR_PROVEEDOR_FALTANTE = "ORDENAR_PROVEEDOR_FALTANTE"
export const ORDENAR_DISPONIBLES_FALTANTE = "ORDENAR_DISPONIBLES_FALTANTE"
export const ORDENAR_CODIGO_FALTANTE_FILTRADO = "ORDENAR_CODIGO_FALTANTE_FILTRADO"
export const ORDENAR_NOMBRE_FALTANTE_FILTRADO = "ORDENAR_NOMBRE_FALTANTE_FILTRADO"
export const ORDENAR_MARCA_FALTANTE_FILTRADO = "ORDENAR_MARCA_FALTANTE_FILTRADO"
export const ORDENAR_MODELO_FALTANTE_FILTRADO = "ORDENAR_MODELO_FALTANTE_FILTRADO"
export const ORDENAR_RUBRO_FALTANTE_FILTRADO = "ORDENAR_RUBRO_FALTANTE_FILTRADO"
export const ORDENAR_PROVEEDOR_FALTANTE_FILTRADO = "ORDENAR_PROVEEDOR_FALTANTE_FILTRADO"
export const ORDENAR_DISPONIBLES_FALTANTE_FILTRADO = "ORDENAR_DISPONIBLES_FALTANTE_FILTRADO"



//Rubro
export const AGREGAR_RUBRO = "AGREGAR_RUBRO"
export const ERROR_AGREGAR_RUBRO = "ERROR_AGREGAR_RUBRO"
export const OBTENER_RUBROS = "OBTENER_RUBROS"
export const FILTRAR_RUBRO = "FILTRAR_RUBRO"
export const LIMPIAR_RUBRO = "LIMPIAR_RUBRO"
export const ELIMINAR_RUBROS = "ELIMINAR_RUBROS"
//Proveedor
export const AGREGAR_PROVEEDOR = "AGREGAR_PROVEEDOR"
export const ERROR_AGREGAR_PROVEEDOR = "ERROR_AGREGAR_PROVEEDOR"
export const OBTENER_PROVEEDORES = "OBTENER_PROVEEDORES"
export const ELIMINAR_PROVEEDORES = "ELIMINAR_PROVEEDORES"
//Precio Producto
export const PRECIO_VENTA = "PRECIO_VENTA"
export const LIMPIAR_VENTA = "LIMPIAR_VENTA"
// Traer dolar de la API
export const TRAER_DOLAR_BD = "TRAER_DOLAR_BD"


export const LIMPIAR_APP = "LIMPIAR_APP"
