//Autenticacion
export const REGISTRO_EXITOSO = "RREGISTRO_EXITOSO"
export const REGISTRO_ERROR = "REGISTRO_ERROR"
export const LOGIN_EXITOSO = "LOGIN_EXITOSO"
export const LOGIN_ERROR = "LOGIN_ERROR"
export const USUARIO_AUTENTICADO = "USUARIO_AUTENTICADO"
export const CERRAR_SESION = "CERRAR_SESION"
export const LIMPIAR_STATE = "LIMPIAR_STATE"
//Alerta
export const OCULTAR_ALERTA = "OCULTAR_ALERTA"
//Producto
export const AGREGAR_PRODUCTO = "AGREGAR_PRODUCTO"
export const ERROR_AGREGAR_PRODUCTO = "ERROR_AGREGAR_PRODUCTO"
export const OBTENER_PRODUCTOS = "OBTENER_PRODUCTOS"
export const PRODUCTOS_CAMBIADOS = "PRODUCTOS_CAMBIADOS"
export const PRODUCTO_ACTUAL = "PRODUCTO_ACTUAL"
export const EDITAR_PRODUCTO = "EDITAR_PRODUCTO"
export const LIMPIAR_SELECCIONADO = "LIMPIAR_SELECCIONADO"
export const ELIMINAR_PRODUCTO = "ELIMINAR_PRODUCTO"
export const FILTRAR_PRODUCTO = "FILTRAR_PRODUCTO"
export const ELIMINAR_PRODUCTOS = "ELIMINAR_PRODUCTOS"
export const ORDENAR_CODIGO = "ORDENAR_CODIGO"
export const ORDENAR_PRECIO = "ORDENAR_PRECIO"
export const LIMPIAR_APP = "LIMPIAR_APP"

//Faltantes
export const AGREGAR_FALTANTE = "AGREGAR_FALTANTE"
export const ORDENAR_CODIGO_FALTANTE = "ORDENAR_CODIGO_FALTANTE"
export const ELIMINAR_FALTANTE = "ELIMINAR_FALTANTE"
export const TRAER_FALTANTES = "TRAER_FALTANTES"



//Rubro
export const AGREGAR_RUBRO = "AGREGAR_RUBRO"
export const ERROR_AGREGAR_RUBRO = "ERROR_AGREGAR_RUBRO"
export const OBTENER_RUBROS = "OBTENER_RUBROS"
export const FILTRAR_RUBRO = "FILTRAR_RUBRO"
export const LIMPIAR_RUBRO = "LIMPIAR_RUBRO"
export const ELIMINAR_RUBROS = "ELIMINAR_RUBROS"
//Proveedor
export const AGREGAR_PROVEEDOR = "AGREGAR_PROVEEDOR"
export const ERROR_AGREGAR_PROVEEDOR = "ERROR_AGREGAR_PROVEEDOR"
export const OBTENER_PROVEEDORES = "OBTENER_PROVEEDORES"
export const ELIMINAR_PROVEEDORES = "ELIMINAR_PROVEEDORES"
//Precio Producto
export const PRECIO_VENTA = "PRECIO_VENTA"
export const LIMPIAR_VENTA = "LIMPIAR_VENTA"
// Traer dolar de la API
export const TRAER_DOLAR_BD = "TRAER_DOLAR_BD"


//Imagen
export const MOSTRAR_ALERTA_APP = "MOSTRAR_ALERTA_APP"
export const OCULTAR_ALERTA_APP = "OCULTAR_ALERTA_APP"

export const SUBIR_ARCHIVO = "SUBIR_ARCHIVO"
export const SUBIR_ARCHIVO_EXITO = "SUBIR_ARCHIVO_EXITO"
export const SUBIR_ARCHIVO_ERROR = "SUBIR_ARCHIVO_ERROR"

export const AGREGAR_PASSWORD = "AGREGAR_PASSWORD"
export const AGREGAR_DESCARGAS = "AGREGAR_DESCARGAS"

export const CREAR_ENLACE_EXITO = "CREAR_ENLACE_EXITO"
export const CREAR_ENLACE_ERROR = "CREAR_ENLACE_ERROR"

export const LIMPIAR_STATE_APP = "LIMPIAR_STATE_APP"



